/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AchadosRouteImport } from './routes/achados'
import { Route as ImpactoRouteImport } from './routes/impacto'
import { Route as MetodologiaRouteImport } from './routes/metodologia'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AchadosRoute = AchadosRouteImport.update({
  id: '/achados',
  path: '/achados',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactoRoute = ImpactoRouteImport.update({
  id: '/impacto',
  path: '/impacto',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodologiaRoute = MetodologiaRouteImport.update({
  id: '/metodologia',
  path: '/metodologia',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achados': typeof AchadosRoute
  '/impacto': typeof ImpactoRoute
  '/metodologia': typeof MetodologiaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achados': typeof AchadosRoute
  '/impacto': typeof ImpactoRoute
  '/metodologia': typeof MetodologiaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achados': typeof AchadosRoute
  '/impacto': typeof ImpactoRoute
  '/metodologia': typeof MetodologiaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/achados' | '/impacto' | '/metodologia'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/achados' | '/impacto' | '/metodologia'
  id: '__root__' | '/' | '/achados' | '/impacto' | '/metodologia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchadosRoute: typeof AchadosRoute
  ImpactoRoute: typeof ImpactoRoute
  MetodologiaRoute: typeof MetodologiaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achados': {
      id: '/achados'
      path: '/achados'
      fullPath: '/achados'
      preLoaderRoute: typeof AchadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impacto': {
      id: '/impacto'
      path: '/impacto'
      fullPath: '/impacto'
      preLoaderRoute: typeof ImpactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodologia': {
      id: '/metodologia'
      path: '/metodologia'
      fullPath: '/metodologia'
      preLoaderRoute: typeof MetodologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchadosRoute: AchadosRoute,
  ImpactoRoute: ImpactoRoute,
  MetodologiaRoute: MetodologiaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
